name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      Storage_NAME: Storage
      
    runs-on: macos-12

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Prepare Build
      run: brew bundle

    - name: Build
      run: swift build

    - name: Lint
      if: startsWith(github.ref, 'refs/tags/') != true
      run: swiftformat --lint . && swiftlint

    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.Storage_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.Storage_NAME }}PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash)
